# Soru 1 – Liste Metotları

In [2]:
notlar = [85, 92, 76, 92, 100, 76, 85, 92]
#Python’da set() kullanarak tekrarları silebiliriz, sonra tekrar listeye çevirebiliriz:
benzersiz = list(set(notlar))
print("Benzersiz notlar:", benzersiz)
benzersiz = list(set(notlar))
print("Benzersiz notlar:", benzersiz)
#max() ve min() fonksiyonları
en_yuksek = max(notlar)
en_dusuk = min(notlar)
print("En yüksek not:", en_yuksek)
print("En düşük not:", en_dusuk)
#sorted() fonksiyonu
sirali = sorted(notlar)
print("Sıralı notlar:", sirali)


Benzersiz notlar: [100, 92, 85, 76]
Benzersiz notlar: [100, 92, 85, 76]
En yüksek not: 100
En düşük not: 76
Sıralı notlar: [76, 76, 85, 85, 92, 92, 92, 100]


# Soru 2 – Sayılar

In [5]:
def armstrong_mu(sayi):
    # Sayıyı stringe çevirip basamaklarını alıyoruz
    basamaklar = [int(x) for x in str(sayi)]
    
    # Her basamağın küpünü alıp topluyoruz
    toplam = sum([b**3 for b in basamaklar])
    
    # Armstrong kontrolü
    if toplam == sayi:
        return True
    else:
        return False


# Örnek kullanım
print(armstrong_mu(153)) 
print(armstrong_mu(370))  

True
True


# Soru 3 – Kümeler

In [8]:
A = {"Python", "R", "SQL", "Java"}
B = {"C++", "Python", "JavaScript", "SQL"}

# 1) Ortak diller
ortak = A & B
print("Ortak diller:", ortak)

# 2) Sadece A’da olanlar
sadece_A = A - B
print("Sadece A’da olan diller:", sadece_A)

# 3) Birleşim (alfabetik)
birlesim = sorted(A | B)
print("Birleşim (alfabetik):", birlesim)


Ortak diller: {'Python', 'SQL'}
Sadece A’da olan diller: {'R', 'Java'}
Birleşim (alfabetik): ['C++', 'Java', 'JavaScript', 'Python', 'R', 'SQL']


# Soru 4 – Modüller

In [11]:
import random
import statistics

# 1) 1–100 arasında 10 rastgele sayı üret
sayilar = [random.randint(1, 100) for _ in range(10)]
print("Rastgele sayılar:", sayilar)

# 2) Ortalamayı hesapla
ortalama = statistics.mean(sayilar)
print("Ortalama:", ortalama)

# 3) Standart sapmayı hesapla
std_sapma = statistics.stdev(sayilar)
print("Standart sapma:", std_sapma)


Rastgele sayılar: [46, 45, 6, 63, 61, 17, 6, 26, 74, 35]
Ortalama: 37.9
Standart sapma: 24.048330965416753


# Soru 5 – Fonksiyonlar

In [14]:
def kelime_sayaci(metin):
    # Noktalama işaretlerini temizleyelim (basit çözüm)
    for nok in ",.!?;:":
        metin = metin.replace(nok, "")
    
    # Metni kelimelere ayır
    kelimeler = metin.split()
    
    # 1) Toplam kelime sayısı
    toplam = len(kelimeler)
    
    # 2) En uzun kelime
    en_uzun = max(kelimeler, key=len)
    
    # 3) En sık geçen kelime
    # count ile her kelimenin kaç kez geçtiğini say
    en_sik = max(kelimeler, key=kelimeler.count)
    
    return toplam, en_uzun, en_sik


# Örnek kullanım
metin = "Python çok güzel, Python öğrenmek çok eğlenceli!"
sonuc = kelime_sayaci(metin)

print("Toplam kelime sayısı:", sonuc[0])
print("En uzun kelime:", sonuc[1])
print("En sık geçen kelime:", sonuc[2])


Toplam kelime sayısı: 7
En uzun kelime: eğlenceli
En sık geçen kelime: Python


# Soru 6 – Gömülü Fonksiyonlar

In [17]:
sayilar = [5, 12, 7, 18, 24, 3, 16]

# 1) Çift sayıları filtrele
ciftler = list(filter(lambda x: x % 2 == 0, sayilar))
print("Çift sayılar:", ciftler)

# 2) Karelerini bul
kareler = list(map(lambda x: x**2, ciftler))
print("Kareleri:", kareler)

# 3) Azalan sırada sıralama
sirali = sorted(kareler, reverse=True)
print("Azalan sırada:", sirali)


Çift sayılar: [12, 18, 24, 16]
Kareleri: [144, 324, 576, 256]
Azalan sırada: [576, 324, 256, 144]


# Soru 7 – Lambda İfadeleri

In [20]:
kelimeler = ["veri", "bilim", "analiz", "yapayzeka", "python"]

sirali = sorted(kelimeler, key=lambda x: len(x))

print(sirali)


['veri', 'bilim', 'analiz', 'python', 'yapayzeka']


# Soru 8 – Metodlar

In [25]:
import re

def rakam_toplam(metin):
    # Metin içindeki sayıları bul (birden fazla rakam olabilir, örn "12")
    sayilar = re.findall(r"\d+", metin)
    
    # Sayıları integer'a çevirip topla
    toplam = sum(int(s) for s in sayilar)
    return toplam

#Burada \d+ ifadesi:
#\d → rakam demek
#+ → bir veya daha fazla kez tekrar

# Örnek kullanım
print(rakam_toplam("abc12def3"))   # 15
print(rakam_toplam("veri123bilim45"))  # 168 (123+45)
print(rakam_toplam("no number"))   # 0


15
168
0


# Soru 9 – (Ekstra) Numpy 1 

In [30]:
import numpy as np

# 1) 0–50 arasında 10 elemanlı rastgele dizi oluştur
dizi = np.random.randint(0, 51, size=10)
print("Dizi:", dizi)

# 2) Ortalama
ortalama = np.mean(dizi)
print("Ortalama:", ortalama)

# 3) Standart sapma
std_sapma = np.std(dizi)
print("Standart sapma:", std_sapma)

# 4) En büyük değer
en_buyuk = np.max(dizi)
print("En büyük değer:", en_buyuk)
#np.random.randint(0, 51, size=10) → 0–50 arasında 10 rastgele tamsayı üretir.
#np.mean(dizi) → ortalama
#np.std(dizi) → standart sapma
#np.max(dizi) → en büyük değer

Dizi: [ 1  8 42  3 31 31 17 34  6  0]
Ortalama: 17.3
Standart sapma: 14.993665329064806
En büyük değer: 42


# Soru 10 – (Ekstra) Numpy 2


In [33]:
import numpy as np

# 1) 5x5 boyutunda rastgele 0-1 matrisi oluştur
matris = np.random.rand(5,5)
print("Orijinal matris:\n", matris)

# 2) Her sütunun ortalamasını bul
sutun_ortalamalari = np.mean(matris, axis=0)
print("\nSütun ortalamaları:", sutun_ortalamalari)

# 3) 0.5'ten büyük olanları 1, küçük veya eşit olanları 0 yap
binary_matris = np.where(matris > 0.5, 1, 0)
print("\nBinary matris:\n", binary_matris)
#np.mean(matris, axis=0) → sütun bazlı ortalama
#np.where(matris > 0.5, 1, 0) → koşullu atama ile binary matris oluşturuyor

Orijinal matris:
 [[0.21871717 0.70063332 0.3789098  0.75671419 0.18659971]
 [0.7872903  0.33649515 0.98115051 0.49646523 0.64854661]
 [0.00946063 0.27733938 0.79377103 0.67173259 0.84260955]
 [0.76446572 0.87020518 0.81132262 0.38396094 0.05300296]
 [0.85436519 0.66303571 0.31700529 0.44264632 0.44186882]]

Sütun ortalamaları: [0.5268598  0.56954175 0.65643185 0.55030385 0.43452553]

Binary matris:
 [[0 1 0 1 0]
 [1 0 1 0 1]
 [0 0 1 1 1]
 [1 1 1 0 0]
 [1 1 0 0 0]]
